---
title: "Water Potability"
author: "Jake Burnett"
date: "7/31/2021"
output: pdf_document
---

#### *Insert Description and Details of Project*

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import Libraries and Dataset
```{r}
#Graph
library(ggplot2)
library(corrplot)
library(dplyr)
library(tidyverse)
library(rpart)
library(rpart.plot)
```

### Import Dataset
```{r}
water <- water_potability <- read.csv("~/Downloads/water_potability.csv")
summary(water)
```
```{r}
colSums(is.na(water))
```
```{r}
#Check central tendency for variables with missing values
summary(water)
```
```{r replace missing values with means}
water$Sulfate[is.na(water$Sulfate)] <- mean(water$Sulfate,na.rm=TRUE)
water$Trihalomethanes[is.na(water$Trihalomethanes)] <- mean(water$Trihalomethanes,na.rm=TRUE)
water$ph[is.na(water$ph)] <- mean(water$ph,na.rm=TRUE)
```
```{r}
head(water)
```
```{r ph boxplot}
boxplot(ph~Potability,data=water, main="Potability and ph", xlab="Potability", ylab="ph")
```
```{r Hardness boxplot}
boxplot(Hardness~Potability,data=water, main="Potability and Hardness", xlab="Potability", ylab="Hardness")
```
```{r Solids boxplot}
boxplot(Solids~Potability,data=water, main="Potability and Solids", xlab="Potability", ylab="Solids")
```
```{r Chloramines boxplot}
boxplot(Chloramines~Potability,data=water, main="Potability and Chloramines", xlab="Potability", ylab="Chloramines")
```
```{r Sulfate boxplot}
boxplot(Sulfate~Potability,data=water, main="Potability and Sulfate", xlab="Potability", ylab="Sulfate")
```
```{r Conductivity boxplot}
boxplot(Conductivity~Potability,data=water, main="Potability and Conductivity", xlab="Potability", ylab="Conductivity")
```
```{r Orangic_Carbon boxplot}
boxplot(Organic_carbon~Potability,data=water, main="Potability and Organic Carbon", xlab="Potability", ylab="Organic Carbon")
```
```{r Trihalomethanes boxplot}
boxplot(Trihalomethanes~Potability,data=water, main="Potability and Trihalomethanes", xlab="Potability", ylab="Trihalomethanes")
```
```{r Turbidity boxplot}
boxplot(Turbidity~Potability,data=water, main="Potability and Turbidity", xlab="Potability", ylab="Turbidity")
```
```{r}
set.seed(7)
```
```{r}
n <- dim(water)[1]
```
```{r}
water_ind <- runif(n) < 0.8
```
```{r}
water_train <- water[ water_ind, ]
water_test <- water[ !water_ind, ]
```
```{r}
t.test(water_train$Potability,water_test$Potability)
```
```{r}
model01 <- lm(formula = Potability ~ ph + Hardness + Solids + Chloramines + Sulfate + Conductivity + Organic_carbon + Trihalomethanes + Turbidity, data = water_train)
summary(model01)
```
```{r}
model01_test <- lm(formula = Potability ~ ph + Hardness + Solids + Chloramines + Sulfate + Conductivity + Organic_carbon + Trihalomethanes + Turbidity, data = water_test)
summary(model01_test)
```
```{r}
model02 <- lm(formula = Potability ~ Solids + Organic_carbon, data = water_train)
summary(model02)
```
```{r}
model02_test <- lm(formula = Potability ~ Solids + Organic_carbon, data = water_test)
summary(model02_test)
```
```{r}
cust01 <- data.frame(Solids = 20791.319, Organic_carbon = 10.379783)
predict(object = model02, newdata = cust01)
```
```{r}
summary(model02)
```



